[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
edition = "2018"
name = "led-roulette"
version = "0.1.0"

[dependencies]
aux5 = { path = "auxiliary" }

[profile.release]
codegen-units = 1
debug = true
lto = true
